// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo84R8G-MprQ5UlzIxlRzAHAExINM8Dn8',
    appId: '1:19522758604:web:a17db539c57086be621f69',
    messagingSenderId: '19522758604',
    projectId: 'chat-app-6a969',
    authDomain: 'chat-app-6a969.firebaseapp.com',
    storageBucket: 'chat-app-6a969.appspot.com',
    measurementId: 'G-4KJN2VB0F1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRvBoAjs3Omoew9H4VL4ytCMwk5vTY_QU',
    appId: '1:19522758604:android:cf5d668fea41fe3e621f69',
    messagingSenderId: '19522758604',
    projectId: 'chat-app-6a969',
    storageBucket: 'chat-app-6a969.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO3pau246hzi-fUHg3FLqphwLOQHtxQFY',
    appId: '1:19522758604:ios:1a9bfa42852315fc621f69',
    messagingSenderId: '19522758604',
    projectId: 'chat-app-6a969',
    storageBucket: 'chat-app-6a969.appspot.com',
    androidClientId: '19522758604-v1nencl1k1115g17km4j9b0q475q643q.apps.googleusercontent.com',
    iosClientId: '19522758604-0cimngci2gb26d65u42ofe8ruufses5g.apps.googleusercontent.com',
    iosBundleId: 'com.example.standChatApp',
  );
}
